### ISSUE TITLE
Async ignores last last tasks

### ISSUE THREAD

**Issue by vikiival** [kodadot/bao#5]
I found out that in when the app is about to end it does not handle that the `_unfinished_tasks` can spawn other tasks

<img width="1616" alt="Screenshot 2022-01-28 at 12 39 30" src="https://user-images.githubusercontent.com/22471030/151540937-6e975d54-1ffe-4e11-905a-d8686d56b0c2.png">

when i run the app it will finish those 5 tasks however the 3 🔥 tasks should spawn 3 more ❄️ 

```
12:39:46 INFO: [ASYNC OBJECT]: ❄️  200 bafkreiavfaprfpofh754yuiimg5yvetrrlxuy3o7rf4wrzqw75nmi3wtki
12:39:46 INFO: [ASYNC 🔥]: 200 bafkreigujg6s43c52nyx7apkq7hfyk3v4smmmx4ekucltt6pnxaefxtpsq.png
12:39:46 INFO: [ASYNC 🔥]: 200 bafkreicje2sievgnrrk3v6mj5t6famyjbg4gzyrhomdm2dn55kdqtajtb4.png
12:39:46 INFO: [ASYNC 🔥]: 200 bafkreib75jqxadtvzi7amit66b4zhvzoehtq3i722q4fl4pz37v636mmwy.png
12:39:46 INFO: [ASYNC OBJECT]: ❄️  200 bafkreidzj3u2h2rprg2p3walm4zvhtiz3oc52fiojrjwcwwsg6bpsbv6ya
```

The similar issue when there are initially less tasks then the maxsize of the limited set

<img width="1572" alt="Screenshot 2022-01-28 at 12 43 44" src="https://user-images.githubusercontent.com/22471030/151541803-1b4638be-33d4-488a-b1de-f67bb7247ea2.png">

May @unknow112  can check

**Comment by vikiival** [comment]
For testing:
if you do not get enough data 
change the param in `graphql_ago` (in `graphql.py`) from `30` to `240` or so

**Comment by unknow112** [comment]
on it
